/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Action Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ActionDec#getName <em>Name</em>}</li>
 *   <li>{@link hu.bme.mit.depModel.ActionDec#getPortInstance <em>Port Instance</em>}</li>
 *   <li>{@link hu.bme.mit.depModel.ActionDec#getErrorMode <em>Error Mode</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getActionDec()
 * @model
 * @generated
 */
public interface ActionDec extends TransitionFeatureDec
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see hu.bme.mit.depModel.DepModelPackage#getActionDec_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ActionDec#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Port Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port Instance</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port Instance</em>' reference.
   * @see #setPortInstance(PortDec)
   * @see hu.bme.mit.depModel.DepModelPackage#getActionDec_PortInstance()
   * @model
   * @generated
   */
  PortDec getPortInstance();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ActionDec#getPortInstance <em>Port Instance</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port Instance</em>' reference.
   * @see #getPortInstance()
   * @generated
   */
  void setPortInstance(PortDec value);

  /**
   * Returns the value of the '<em><b>Error Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error Mode</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Mode</em>' reference.
   * @see #setErrorMode(ErrorModes)
   * @see hu.bme.mit.depModel.DepModelPackage#getActionDec_ErrorMode()
   * @model
   * @generated
   */
  ErrorModes getErrorMode();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ActionDec#getErrorMode <em>Error Mode</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error Mode</em>' reference.
   * @see #getErrorMode()
   * @generated
   */
  void setErrorMode(ErrorModes value);

} // ActionDec
