/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Component Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ComponentType#getComponentFeatures <em>Component Features</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getComponentType()
 * @model
 * @generated
 */
public interface ComponentType extends SysFeaturesDec
{
  /**
   * Returns the value of the '<em><b>Component Features</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.depModel.ComponentFeaturesDec}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Features</em>' containment reference list.
   * @see hu.bme.mit.depModel.DepModelPackage#getComponentType_ComponentFeatures()
   * @model containment="true"
   * @generated
   */
  EList<ComponentFeaturesDec> getComponentFeatures();

} // ComponentType
