/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see hu.bme.mit.depModel.DepModelFactory
 * @model kind="package"
 * @generated
 */
public interface DepModelPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "depModel";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.bme.hu/mit/DepModel";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "depModel";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DepModelPackage eINSTANCE = hu.bme.mit.depModel.impl.DepModelPackageImpl.init();

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.DepModelImpl <em>Dep Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.DepModelImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getDepModel()
   * @generated
   */
  int DEP_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Dep Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DEP_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.AbstractElementImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getAbstractElement()
   * @generated
   */
  int ABSTRACT_ELEMENT = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Abstract Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ABSTRACT_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.PortTypeImpl <em>Port Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.PortTypeImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortType()
   * @generated
   */
  int PORT_TYPE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_TYPE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>EModes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_TYPE__EMODES = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Port Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ErrorModesImpl <em>Error Modes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ErrorModesImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModes()
   * @generated
   */
  int ERROR_MODES = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODES__NAME = 0;

  /**
   * The number of structural features of the '<em>Error Modes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ComponentModelDecImpl <em>Component Model Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ComponentModelDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentModelDec()
   * @generated
   */
  int COMPONENT_MODEL_DEC = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_MODEL_DEC__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>Component Model Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_MODEL_DEC_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SystemConnDecImpl <em>System Conn Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SystemConnDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemConnDec()
   * @generated
   */
  int SYSTEM_CONN_DEC = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__NAME = COMPONENT_MODEL_DEC__NAME;

  /**
   * The feature id for the '<em><b>Source System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__SOURCE_SYSTEM = COMPONENT_MODEL_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__SOURCE_PORT = COMPONENT_MODEL_DEC_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target System</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__TARGET_SYSTEM = COMPONENT_MODEL_DEC_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__TARGET_PORT = COMPONENT_MODEL_DEC_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Prob</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC__PROB = COMPONENT_MODEL_DEC_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>System Conn Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_CONN_DEC_FEATURE_COUNT = COMPONENT_MODEL_DEC_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SystemDecImpl <em>System Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SystemDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemDec()
   * @generated
   */
  int SYSTEM_DEC = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEC__NAME = COMPONENT_MODEL_DEC__NAME;

  /**
   * The feature id for the '<em><b>Sys Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEC__SYS_FEATURES = COMPONENT_MODEL_DEC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>System Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_DEC_FEATURE_COUNT = COMPONENT_MODEL_DEC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SysFeaturesDecImpl <em>Sys Features Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SysFeaturesDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSysFeaturesDec()
   * @generated
   */
  int SYS_FEATURES_DEC = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYS_FEATURES_DEC__NAME = 0;

  /**
   * The number of structural features of the '<em>Sys Features Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYS_FEATURES_DEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SystemPortDecImpl <em>System Port Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SystemPortDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortDec()
   * @generated
   */
  int SYSTEM_PORT_DEC = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_DEC__NAME = SYS_FEATURES_DEC__NAME;

  /**
   * The number of structural features of the '<em>System Port Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_DEC_FEATURE_COUNT = SYS_FEATURES_DEC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SystemPortInImpl <em>System Port In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SystemPortInImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortIn()
   * @generated
   */
  int SYSTEM_PORT_IN = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_IN__NAME = SYSTEM_PORT_DEC__NAME;

  /**
   * The feature id for the '<em><b>In Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_IN__IN_COMP = SYSTEM_PORT_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>In Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_IN__IN_PORT = SYSTEM_PORT_DEC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>System Port In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_IN_FEATURE_COUNT = SYSTEM_PORT_DEC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.SystemPortOutImpl <em>System Port Out</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.SystemPortOutImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortOut()
   * @generated
   */
  int SYSTEM_PORT_OUT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_OUT__NAME = SYSTEM_PORT_DEC__NAME;

  /**
   * The feature id for the '<em><b>Out Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_OUT__OUT_COMP = SYSTEM_PORT_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Out Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_OUT__OUT_PORT = SYSTEM_PORT_DEC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>System Port Out</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_PORT_OUT_FEATURE_COUNT = SYSTEM_PORT_DEC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ComponentConnDecImpl <em>Component Conn Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ComponentConnDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentConnDec()
   * @generated
   */
  int COMPONENT_CONN_DEC = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__NAME = SYS_FEATURES_DEC__NAME;

  /**
   * The feature id for the '<em><b>Source Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__SOURCE_COMP = SYS_FEATURES_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__SOURCE_PORT = SYS_FEATURES_DEC_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Target Comp</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__TARGET_COMP = SYS_FEATURES_DEC_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Target Port</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__TARGET_PORT = SYS_FEATURES_DEC_FEATURE_COUNT + 3;

  /**
   * The feature id for the '<em><b>Prob</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC__PROB = SYS_FEATURES_DEC_FEATURE_COUNT + 4;

  /**
   * The number of structural features of the '<em>Component Conn Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_CONN_DEC_FEATURE_COUNT = SYS_FEATURES_DEC_FEATURE_COUNT + 5;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ComponentImplImpl <em>Component Impl</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ComponentImplImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentImpl()
   * @generated
   */
  int COMPONENT_IMPL = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_IMPL__NAME = SYS_FEATURES_DEC__NAME;

  /**
   * The feature id for the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_IMPL__SUPER_TYPE = SYS_FEATURES_DEC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Component Impl</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_IMPL_FEATURE_COUNT = SYS_FEATURES_DEC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ComponentTypeImpl <em>Component Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ComponentTypeImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentType()
   * @generated
   */
  int COMPONENT_TYPE = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_TYPE__NAME = ABSTRACT_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Component Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_TYPE__COMPONENT_FEATURES = ABSTRACT_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Component Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_TYPE_FEATURE_COUNT = ABSTRACT_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ComponentFeaturesDecImpl <em>Component Features Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ComponentFeaturesDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentFeaturesDec()
   * @generated
   */
  int COMPONENT_FEATURES_DEC = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURES_DEC__NAME = 0;

  /**
   * The number of structural features of the '<em>Component Features Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPONENT_FEATURES_DEC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.PortDecImpl <em>Port Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.PortDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortDec()
   * @generated
   */
  int PORT_DEC = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_DEC__NAME = COMPONENT_FEATURES_DEC__NAME;

  /**
   * The number of structural features of the '<em>Port Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_DEC_FEATURE_COUNT = COMPONENT_FEATURES_DEC_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.PortInImpl <em>Port In</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.PortInImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortIn()
   * @generated
   */
  int PORT_IN = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_IN__NAME = PORT_DEC__NAME;

  /**
   * The feature id for the '<em><b>Port In Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_IN__PORT_IN_SUPER_TYPE = PORT_DEC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Port In</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_IN_FEATURE_COUNT = PORT_DEC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.PortOutImpl <em>Port Out</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.PortOutImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortOut()
   * @generated
   */
  int PORT_OUT = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_OUT__NAME = PORT_DEC__NAME;

  /**
   * The feature id for the '<em><b>Port Out Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_OUT__PORT_OUT_SUPER_TYPE = PORT_DEC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Port Out</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PORT_OUT_FEATURE_COUNT = PORT_DEC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ErrorModelDecImpl <em>Error Model Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ErrorModelDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModelDec()
   * @generated
   */
  int ERROR_MODEL_DEC = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_DEC__NAME = COMPONENT_FEATURES_DEC__NAME;

  /**
   * The feature id for the '<em><b>Emodel Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_DEC__EMODEL_ELEMENTS = COMPONENT_FEATURES_DEC_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Error Model Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_DEC_FEATURE_COUNT = COMPONENT_FEATURES_DEC_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ErrorModelElementImpl <em>Error Model Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ErrorModelElementImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModelElement()
   * @generated
   */
  int ERROR_MODEL_ELEMENT = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_ELEMENT__NAME = 0;

  /**
   * The number of structural features of the '<em>Error Model Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ERROR_MODEL_ELEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.StateImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getState()
   * @generated
   */
  int STATE = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = ERROR_MODEL_ELEMENT__NAME;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = ERROR_MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.TransitionDecImpl <em>Transition Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.TransitionDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionDec()
   * @generated
   */
  int TRANSITION_DEC = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_DEC__NAME = ERROR_MODEL_ELEMENT__NAME;

  /**
   * The feature id for the '<em><b>Trans Features</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_DEC__TRANS_FEATURES = ERROR_MODEL_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Transition Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_DEC_FEATURE_COUNT = ERROR_MODEL_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.TransitionFeatureDecImpl <em>Transition Feature Dec</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.TransitionFeatureDecImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionFeatureDec()
   * @generated
   */
  int TRANSITION_FEATURE_DEC = 22;

  /**
   * The number of structural features of the '<em>Transition Feature Dec</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_DEC_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.TransitionStateImpl <em>Transition State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.TransitionStateImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionState()
   * @generated
   */
  int TRANSITION_STATE = 23;

  /**
   * The feature id for the '<em><b>Source State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_STATE__SOURCE_STATE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Target State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_STATE__TARGET_STATE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Transition State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_STATE_FEATURE_COUNT = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.TriggerImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 24;

  /**
   * The feature id for the '<em><b>Port Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__PORT_INSTANCE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Error Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__ERROR_MODE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.ActionImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getAction()
   * @generated
   */
  int ACTION = 25;

  /**
   * The feature id for the '<em><b>Port Instance</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__PORT_INSTANCE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Error Mode</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__ERROR_MODE = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link hu.bme.mit.depModel.impl.OccurrenceImpl <em>Occurrence</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see hu.bme.mit.depModel.impl.OccurrenceImpl
   * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getOccurrence()
   * @generated
   */
  int OCCURRENCE = 26;

  /**
   * The number of structural features of the '<em>Occurrence</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURRENCE_FEATURE_COUNT = TRANSITION_FEATURE_DEC_FEATURE_COUNT + 0;


  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.DepModel <em>Dep Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dep Model</em>'.
   * @see hu.bme.mit.depModel.DepModel
   * @generated
   */
  EClass getDepModel();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.DepModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see hu.bme.mit.depModel.DepModel#getElements()
   * @see #getDepModel()
   * @generated
   */
  EReference getDepModel_Elements();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Abstract Element</em>'.
   * @see hu.bme.mit.depModel.AbstractElement
   * @generated
   */
  EClass getAbstractElement();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.AbstractElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.depModel.AbstractElement#getName()
   * @see #getAbstractElement()
   * @generated
   */
  EAttribute getAbstractElement_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.PortType <em>Port Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port Type</em>'.
   * @see hu.bme.mit.depModel.PortType
   * @generated
   */
  EClass getPortType();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.PortType#getEModes <em>EModes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>EModes</em>'.
   * @see hu.bme.mit.depModel.PortType#getEModes()
   * @see #getPortType()
   * @generated
   */
  EReference getPortType_EModes();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ErrorModes <em>Error Modes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Modes</em>'.
   * @see hu.bme.mit.depModel.ErrorModes
   * @generated
   */
  EClass getErrorModes();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.ErrorModes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.depModel.ErrorModes#getName()
   * @see #getErrorModes()
   * @generated
   */
  EAttribute getErrorModes_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ComponentModelDec <em>Component Model Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Model Dec</em>'.
   * @see hu.bme.mit.depModel.ComponentModelDec
   * @generated
   */
  EClass getComponentModelDec();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SystemConnDec <em>System Conn Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Conn Dec</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec
   * @generated
   */
  EClass getSystemConnDec();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemConnDec#getSourceSystem <em>Source System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source System</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec#getSourceSystem()
   * @see #getSystemConnDec()
   * @generated
   */
  EReference getSystemConnDec_SourceSystem();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemConnDec#getSourcePort <em>Source Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Port</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec#getSourcePort()
   * @see #getSystemConnDec()
   * @generated
   */
  EReference getSystemConnDec_SourcePort();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemConnDec#getTargetSystem <em>Target System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target System</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec#getTargetSystem()
   * @see #getSystemConnDec()
   * @generated
   */
  EReference getSystemConnDec_TargetSystem();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemConnDec#getTargetPort <em>Target Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Port</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec#getTargetPort()
   * @see #getSystemConnDec()
   * @generated
   */
  EReference getSystemConnDec_TargetPort();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.SystemConnDec#getProb <em>Prob</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prob</em>'.
   * @see hu.bme.mit.depModel.SystemConnDec#getProb()
   * @see #getSystemConnDec()
   * @generated
   */
  EAttribute getSystemConnDec_Prob();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SystemDec <em>System Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Dec</em>'.
   * @see hu.bme.mit.depModel.SystemDec
   * @generated
   */
  EClass getSystemDec();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.SystemDec#getSysFeatures <em>Sys Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sys Features</em>'.
   * @see hu.bme.mit.depModel.SystemDec#getSysFeatures()
   * @see #getSystemDec()
   * @generated
   */
  EReference getSystemDec_SysFeatures();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SysFeaturesDec <em>Sys Features Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sys Features Dec</em>'.
   * @see hu.bme.mit.depModel.SysFeaturesDec
   * @generated
   */
  EClass getSysFeaturesDec();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.SysFeaturesDec#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.depModel.SysFeaturesDec#getName()
   * @see #getSysFeaturesDec()
   * @generated
   */
  EAttribute getSysFeaturesDec_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SystemPortDec <em>System Port Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Port Dec</em>'.
   * @see hu.bme.mit.depModel.SystemPortDec
   * @generated
   */
  EClass getSystemPortDec();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SystemPortIn <em>System Port In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Port In</em>'.
   * @see hu.bme.mit.depModel.SystemPortIn
   * @generated
   */
  EClass getSystemPortIn();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemPortIn#getInComp <em>In Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>In Comp</em>'.
   * @see hu.bme.mit.depModel.SystemPortIn#getInComp()
   * @see #getSystemPortIn()
   * @generated
   */
  EReference getSystemPortIn_InComp();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemPortIn#getInPort <em>In Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>In Port</em>'.
   * @see hu.bme.mit.depModel.SystemPortIn#getInPort()
   * @see #getSystemPortIn()
   * @generated
   */
  EReference getSystemPortIn_InPort();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.SystemPortOut <em>System Port Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Port Out</em>'.
   * @see hu.bme.mit.depModel.SystemPortOut
   * @generated
   */
  EClass getSystemPortOut();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemPortOut#getOutComp <em>Out Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Out Comp</em>'.
   * @see hu.bme.mit.depModel.SystemPortOut#getOutComp()
   * @see #getSystemPortOut()
   * @generated
   */
  EReference getSystemPortOut_OutComp();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.SystemPortOut#getOutPort <em>Out Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Out Port</em>'.
   * @see hu.bme.mit.depModel.SystemPortOut#getOutPort()
   * @see #getSystemPortOut()
   * @generated
   */
  EReference getSystemPortOut_OutPort();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ComponentConnDec <em>Component Conn Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Conn Dec</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec
   * @generated
   */
  EClass getComponentConnDec();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.ComponentConnDec#getSourceComp <em>Source Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Comp</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec#getSourceComp()
   * @see #getComponentConnDec()
   * @generated
   */
  EReference getComponentConnDec_SourceComp();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.ComponentConnDec#getSourcePort <em>Source Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source Port</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec#getSourcePort()
   * @see #getComponentConnDec()
   * @generated
   */
  EReference getComponentConnDec_SourcePort();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.ComponentConnDec#getTargetComp <em>Target Comp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Comp</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec#getTargetComp()
   * @see #getComponentConnDec()
   * @generated
   */
  EReference getComponentConnDec_TargetComp();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.ComponentConnDec#getTargetPort <em>Target Port</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target Port</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec#getTargetPort()
   * @see #getComponentConnDec()
   * @generated
   */
  EReference getComponentConnDec_TargetPort();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.ComponentConnDec#getProb <em>Prob</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prob</em>'.
   * @see hu.bme.mit.depModel.ComponentConnDec#getProb()
   * @see #getComponentConnDec()
   * @generated
   */
  EAttribute getComponentConnDec_Prob();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ComponentImpl <em>Component Impl</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Impl</em>'.
   * @see hu.bme.mit.depModel.ComponentImpl
   * @generated
   */
  EClass getComponentImpl();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.ComponentImpl#getSuperType <em>Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Type</em>'.
   * @see hu.bme.mit.depModel.ComponentImpl#getSuperType()
   * @see #getComponentImpl()
   * @generated
   */
  EReference getComponentImpl_SuperType();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ComponentType <em>Component Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Type</em>'.
   * @see hu.bme.mit.depModel.ComponentType
   * @generated
   */
  EClass getComponentType();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.ComponentType#getComponentFeatures <em>Component Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Component Features</em>'.
   * @see hu.bme.mit.depModel.ComponentType#getComponentFeatures()
   * @see #getComponentType()
   * @generated
   */
  EReference getComponentType_ComponentFeatures();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ComponentFeaturesDec <em>Component Features Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Component Features Dec</em>'.
   * @see hu.bme.mit.depModel.ComponentFeaturesDec
   * @generated
   */
  EClass getComponentFeaturesDec();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.ComponentFeaturesDec#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.depModel.ComponentFeaturesDec#getName()
   * @see #getComponentFeaturesDec()
   * @generated
   */
  EAttribute getComponentFeaturesDec_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.PortDec <em>Port Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port Dec</em>'.
   * @see hu.bme.mit.depModel.PortDec
   * @generated
   */
  EClass getPortDec();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.PortIn <em>Port In</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port In</em>'.
   * @see hu.bme.mit.depModel.PortIn
   * @generated
   */
  EClass getPortIn();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.PortIn#getPortInSuperType <em>Port In Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Port In Super Type</em>'.
   * @see hu.bme.mit.depModel.PortIn#getPortInSuperType()
   * @see #getPortIn()
   * @generated
   */
  EReference getPortIn_PortInSuperType();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.PortOut <em>Port Out</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Port Out</em>'.
   * @see hu.bme.mit.depModel.PortOut
   * @generated
   */
  EClass getPortOut();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.PortOut#getPortOutSuperType <em>Port Out Super Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Port Out Super Type</em>'.
   * @see hu.bme.mit.depModel.PortOut#getPortOutSuperType()
   * @see #getPortOut()
   * @generated
   */
  EReference getPortOut_PortOutSuperType();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ErrorModelDec <em>Error Model Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Model Dec</em>'.
   * @see hu.bme.mit.depModel.ErrorModelDec
   * @generated
   */
  EClass getErrorModelDec();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.ErrorModelDec#getEmodelElements <em>Emodel Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Emodel Elements</em>'.
   * @see hu.bme.mit.depModel.ErrorModelDec#getEmodelElements()
   * @see #getErrorModelDec()
   * @generated
   */
  EReference getErrorModelDec_EmodelElements();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.ErrorModelElement <em>Error Model Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Error Model Element</em>'.
   * @see hu.bme.mit.depModel.ErrorModelElement
   * @generated
   */
  EClass getErrorModelElement();

  /**
   * Returns the meta object for the attribute '{@link hu.bme.mit.depModel.ErrorModelElement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see hu.bme.mit.depModel.ErrorModelElement#getName()
   * @see #getErrorModelElement()
   * @generated
   */
  EAttribute getErrorModelElement_Name();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see hu.bme.mit.depModel.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.TransitionDec <em>Transition Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Dec</em>'.
   * @see hu.bme.mit.depModel.TransitionDec
   * @generated
   */
  EClass getTransitionDec();

  /**
   * Returns the meta object for the containment reference list '{@link hu.bme.mit.depModel.TransitionDec#getTransFeatures <em>Trans Features</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Trans Features</em>'.
   * @see hu.bme.mit.depModel.TransitionDec#getTransFeatures()
   * @see #getTransitionDec()
   * @generated
   */
  EReference getTransitionDec_TransFeatures();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.TransitionFeatureDec <em>Transition Feature Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition Feature Dec</em>'.
   * @see hu.bme.mit.depModel.TransitionFeatureDec
   * @generated
   */
  EClass getTransitionFeatureDec();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.TransitionState <em>Transition State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition State</em>'.
   * @see hu.bme.mit.depModel.TransitionState
   * @generated
   */
  EClass getTransitionState();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.TransitionState#getSourceState <em>Source State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source State</em>'.
   * @see hu.bme.mit.depModel.TransitionState#getSourceState()
   * @see #getTransitionState()
   * @generated
   */
  EReference getTransitionState_SourceState();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.TransitionState#getTargetState <em>Target State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Target State</em>'.
   * @see hu.bme.mit.depModel.TransitionState#getTargetState()
   * @see #getTransitionState()
   * @generated
   */
  EReference getTransitionState_TargetState();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see hu.bme.mit.depModel.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.Trigger#getPortInstance <em>Port Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Port Instance</em>'.
   * @see hu.bme.mit.depModel.Trigger#getPortInstance()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_PortInstance();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.Trigger#getErrorMode <em>Error Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Error Mode</em>'.
   * @see hu.bme.mit.depModel.Trigger#getErrorMode()
   * @see #getTrigger()
   * @generated
   */
  EReference getTrigger_ErrorMode();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see hu.bme.mit.depModel.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.Action#getPortInstance <em>Port Instance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Port Instance</em>'.
   * @see hu.bme.mit.depModel.Action#getPortInstance()
   * @see #getAction()
   * @generated
   */
  EReference getAction_PortInstance();

  /**
   * Returns the meta object for the reference '{@link hu.bme.mit.depModel.Action#getErrorMode <em>Error Mode</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Error Mode</em>'.
   * @see hu.bme.mit.depModel.Action#getErrorMode()
   * @see #getAction()
   * @generated
   */
  EReference getAction_ErrorMode();

  /**
   * Returns the meta object for class '{@link hu.bme.mit.depModel.Occurrence <em>Occurrence</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occurrence</em>'.
   * @see hu.bme.mit.depModel.Occurrence
   * @generated
   */
  EClass getOccurrence();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  DepModelFactory getDepModelFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.DepModelImpl <em>Dep Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.DepModelImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getDepModel()
     * @generated
     */
    EClass DEP_MODEL = eINSTANCE.getDepModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DEP_MODEL__ELEMENTS = eINSTANCE.getDepModel_Elements();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.AbstractElementImpl <em>Abstract Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.AbstractElementImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getAbstractElement()
     * @generated
     */
    EClass ABSTRACT_ELEMENT = eINSTANCE.getAbstractElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ABSTRACT_ELEMENT__NAME = eINSTANCE.getAbstractElement_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.PortTypeImpl <em>Port Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.PortTypeImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortType()
     * @generated
     */
    EClass PORT_TYPE = eINSTANCE.getPortType();

    /**
     * The meta object literal for the '<em><b>EModes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT_TYPE__EMODES = eINSTANCE.getPortType_EModes();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ErrorModesImpl <em>Error Modes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ErrorModesImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModes()
     * @generated
     */
    EClass ERROR_MODES = eINSTANCE.getErrorModes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ERROR_MODES__NAME = eINSTANCE.getErrorModes_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ComponentModelDecImpl <em>Component Model Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ComponentModelDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentModelDec()
     * @generated
     */
    EClass COMPONENT_MODEL_DEC = eINSTANCE.getComponentModelDec();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SystemConnDecImpl <em>System Conn Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SystemConnDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemConnDec()
     * @generated
     */
    EClass SYSTEM_CONN_DEC = eINSTANCE.getSystemConnDec();

    /**
     * The meta object literal for the '<em><b>Source System</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_CONN_DEC__SOURCE_SYSTEM = eINSTANCE.getSystemConnDec_SourceSystem();

    /**
     * The meta object literal for the '<em><b>Source Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_CONN_DEC__SOURCE_PORT = eINSTANCE.getSystemConnDec_SourcePort();

    /**
     * The meta object literal for the '<em><b>Target System</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_CONN_DEC__TARGET_SYSTEM = eINSTANCE.getSystemConnDec_TargetSystem();

    /**
     * The meta object literal for the '<em><b>Target Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_CONN_DEC__TARGET_PORT = eINSTANCE.getSystemConnDec_TargetPort();

    /**
     * The meta object literal for the '<em><b>Prob</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_CONN_DEC__PROB = eINSTANCE.getSystemConnDec_Prob();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SystemDecImpl <em>System Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SystemDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemDec()
     * @generated
     */
    EClass SYSTEM_DEC = eINSTANCE.getSystemDec();

    /**
     * The meta object literal for the '<em><b>Sys Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_DEC__SYS_FEATURES = eINSTANCE.getSystemDec_SysFeatures();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SysFeaturesDecImpl <em>Sys Features Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SysFeaturesDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSysFeaturesDec()
     * @generated
     */
    EClass SYS_FEATURES_DEC = eINSTANCE.getSysFeaturesDec();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYS_FEATURES_DEC__NAME = eINSTANCE.getSysFeaturesDec_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SystemPortDecImpl <em>System Port Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SystemPortDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortDec()
     * @generated
     */
    EClass SYSTEM_PORT_DEC = eINSTANCE.getSystemPortDec();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SystemPortInImpl <em>System Port In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SystemPortInImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortIn()
     * @generated
     */
    EClass SYSTEM_PORT_IN = eINSTANCE.getSystemPortIn();

    /**
     * The meta object literal for the '<em><b>In Comp</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_PORT_IN__IN_COMP = eINSTANCE.getSystemPortIn_InComp();

    /**
     * The meta object literal for the '<em><b>In Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_PORT_IN__IN_PORT = eINSTANCE.getSystemPortIn_InPort();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.SystemPortOutImpl <em>System Port Out</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.SystemPortOutImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getSystemPortOut()
     * @generated
     */
    EClass SYSTEM_PORT_OUT = eINSTANCE.getSystemPortOut();

    /**
     * The meta object literal for the '<em><b>Out Comp</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_PORT_OUT__OUT_COMP = eINSTANCE.getSystemPortOut_OutComp();

    /**
     * The meta object literal for the '<em><b>Out Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_PORT_OUT__OUT_PORT = eINSTANCE.getSystemPortOut_OutPort();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ComponentConnDecImpl <em>Component Conn Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ComponentConnDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentConnDec()
     * @generated
     */
    EClass COMPONENT_CONN_DEC = eINSTANCE.getComponentConnDec();

    /**
     * The meta object literal for the '<em><b>Source Comp</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONN_DEC__SOURCE_COMP = eINSTANCE.getComponentConnDec_SourceComp();

    /**
     * The meta object literal for the '<em><b>Source Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONN_DEC__SOURCE_PORT = eINSTANCE.getComponentConnDec_SourcePort();

    /**
     * The meta object literal for the '<em><b>Target Comp</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONN_DEC__TARGET_COMP = eINSTANCE.getComponentConnDec_TargetComp();

    /**
     * The meta object literal for the '<em><b>Target Port</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_CONN_DEC__TARGET_PORT = eINSTANCE.getComponentConnDec_TargetPort();

    /**
     * The meta object literal for the '<em><b>Prob</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_CONN_DEC__PROB = eINSTANCE.getComponentConnDec_Prob();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ComponentImplImpl <em>Component Impl</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ComponentImplImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentImpl()
     * @generated
     */
    EClass COMPONENT_IMPL = eINSTANCE.getComponentImpl();

    /**
     * The meta object literal for the '<em><b>Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_IMPL__SUPER_TYPE = eINSTANCE.getComponentImpl_SuperType();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ComponentTypeImpl <em>Component Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ComponentTypeImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentType()
     * @generated
     */
    EClass COMPONENT_TYPE = eINSTANCE.getComponentType();

    /**
     * The meta object literal for the '<em><b>Component Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPONENT_TYPE__COMPONENT_FEATURES = eINSTANCE.getComponentType_ComponentFeatures();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ComponentFeaturesDecImpl <em>Component Features Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ComponentFeaturesDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getComponentFeaturesDec()
     * @generated
     */
    EClass COMPONENT_FEATURES_DEC = eINSTANCE.getComponentFeaturesDec();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPONENT_FEATURES_DEC__NAME = eINSTANCE.getComponentFeaturesDec_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.PortDecImpl <em>Port Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.PortDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortDec()
     * @generated
     */
    EClass PORT_DEC = eINSTANCE.getPortDec();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.PortInImpl <em>Port In</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.PortInImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortIn()
     * @generated
     */
    EClass PORT_IN = eINSTANCE.getPortIn();

    /**
     * The meta object literal for the '<em><b>Port In Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT_IN__PORT_IN_SUPER_TYPE = eINSTANCE.getPortIn_PortInSuperType();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.PortOutImpl <em>Port Out</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.PortOutImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getPortOut()
     * @generated
     */
    EClass PORT_OUT = eINSTANCE.getPortOut();

    /**
     * The meta object literal for the '<em><b>Port Out Super Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PORT_OUT__PORT_OUT_SUPER_TYPE = eINSTANCE.getPortOut_PortOutSuperType();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ErrorModelDecImpl <em>Error Model Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ErrorModelDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModelDec()
     * @generated
     */
    EClass ERROR_MODEL_DEC = eINSTANCE.getErrorModelDec();

    /**
     * The meta object literal for the '<em><b>Emodel Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ERROR_MODEL_DEC__EMODEL_ELEMENTS = eINSTANCE.getErrorModelDec_EmodelElements();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ErrorModelElementImpl <em>Error Model Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ErrorModelElementImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getErrorModelElement()
     * @generated
     */
    EClass ERROR_MODEL_ELEMENT = eINSTANCE.getErrorModelElement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ERROR_MODEL_ELEMENT__NAME = eINSTANCE.getErrorModelElement_Name();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.StateImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.TransitionDecImpl <em>Transition Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.TransitionDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionDec()
     * @generated
     */
    EClass TRANSITION_DEC = eINSTANCE.getTransitionDec();

    /**
     * The meta object literal for the '<em><b>Trans Features</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_DEC__TRANS_FEATURES = eINSTANCE.getTransitionDec_TransFeatures();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.TransitionFeatureDecImpl <em>Transition Feature Dec</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.TransitionFeatureDecImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionFeatureDec()
     * @generated
     */
    EClass TRANSITION_FEATURE_DEC = eINSTANCE.getTransitionFeatureDec();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.TransitionStateImpl <em>Transition State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.TransitionStateImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTransitionState()
     * @generated
     */
    EClass TRANSITION_STATE = eINSTANCE.getTransitionState();

    /**
     * The meta object literal for the '<em><b>Source State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_STATE__SOURCE_STATE = eINSTANCE.getTransitionState_SourceState();

    /**
     * The meta object literal for the '<em><b>Target State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION_STATE__TARGET_STATE = eINSTANCE.getTransitionState_TargetState();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.TriggerImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Port Instance</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__PORT_INSTANCE = eINSTANCE.getTrigger_PortInstance();

    /**
     * The meta object literal for the '<em><b>Error Mode</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIGGER__ERROR_MODE = eINSTANCE.getTrigger_ErrorMode();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.ActionImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Port Instance</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__PORT_INSTANCE = eINSTANCE.getAction_PortInstance();

    /**
     * The meta object literal for the '<em><b>Error Mode</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__ERROR_MODE = eINSTANCE.getAction_ErrorMode();

    /**
     * The meta object literal for the '{@link hu.bme.mit.depModel.impl.OccurrenceImpl <em>Occurrence</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see hu.bme.mit.depModel.impl.OccurrenceImpl
     * @see hu.bme.mit.depModel.impl.DepModelPackageImpl#getOccurrence()
     * @generated
     */
    EClass OCCURRENCE = eINSTANCE.getOccurrence();

  }

} //DepModelPackage
