/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see hu.bme.mit.depModel.DepModelPackage
 * @generated
 */
public interface DepModelFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  DepModelFactory eINSTANCE = hu.bme.mit.depModel.impl.DepModelFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Dep Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Dep Model</em>'.
   * @generated
   */
  DepModel createDepModel();

  /**
   * Returns a new object of class '<em>Abstract Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Abstract Element</em>'.
   * @generated
   */
  AbstractElement createAbstractElement();

  /**
   * Returns a new object of class '<em>Port Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port Type</em>'.
   * @generated
   */
  PortType createPortType();

  /**
   * Returns a new object of class '<em>Error Modes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Modes</em>'.
   * @generated
   */
  ErrorModes createErrorModes();

  /**
   * Returns a new object of class '<em>Component Model Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Model Dec</em>'.
   * @generated
   */
  ComponentModelDec createComponentModelDec();

  /**
   * Returns a new object of class '<em>System Conn Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Conn Dec</em>'.
   * @generated
   */
  SystemConnDec createSystemConnDec();

  /**
   * Returns a new object of class '<em>System Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Dec</em>'.
   * @generated
   */
  SystemDec createSystemDec();

  /**
   * Returns a new object of class '<em>Sys Features Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Sys Features Dec</em>'.
   * @generated
   */
  SysFeaturesDec createSysFeaturesDec();

  /**
   * Returns a new object of class '<em>System Port Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Port Dec</em>'.
   * @generated
   */
  SystemPortDec createSystemPortDec();

  /**
   * Returns a new object of class '<em>System Port In</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Port In</em>'.
   * @generated
   */
  SystemPortIn createSystemPortIn();

  /**
   * Returns a new object of class '<em>System Port Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>System Port Out</em>'.
   * @generated
   */
  SystemPortOut createSystemPortOut();

  /**
   * Returns a new object of class '<em>Component Conn Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Conn Dec</em>'.
   * @generated
   */
  ComponentConnDec createComponentConnDec();

  /**
   * Returns a new object of class '<em>Component Impl</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Impl</em>'.
   * @generated
   */
  ComponentImpl createComponentImpl();

  /**
   * Returns a new object of class '<em>Component Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Type</em>'.
   * @generated
   */
  ComponentType createComponentType();

  /**
   * Returns a new object of class '<em>Component Features Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Component Features Dec</em>'.
   * @generated
   */
  ComponentFeaturesDec createComponentFeaturesDec();

  /**
   * Returns a new object of class '<em>Port Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port Dec</em>'.
   * @generated
   */
  PortDec createPortDec();

  /**
   * Returns a new object of class '<em>Port In</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port In</em>'.
   * @generated
   */
  PortIn createPortIn();

  /**
   * Returns a new object of class '<em>Port Out</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Port Out</em>'.
   * @generated
   */
  PortOut createPortOut();

  /**
   * Returns a new object of class '<em>Error Model Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Model Dec</em>'.
   * @generated
   */
  ErrorModelDec createErrorModelDec();

  /**
   * Returns a new object of class '<em>Error Model Element</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Error Model Element</em>'.
   * @generated
   */
  ErrorModelElement createErrorModelElement();

  /**
   * Returns a new object of class '<em>State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>State</em>'.
   * @generated
   */
  State createState();

  /**
   * Returns a new object of class '<em>Transition Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition Dec</em>'.
   * @generated
   */
  TransitionDec createTransitionDec();

  /**
   * Returns a new object of class '<em>Transition Feature Dec</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition Feature Dec</em>'.
   * @generated
   */
  TransitionFeatureDec createTransitionFeatureDec();

  /**
   * Returns a new object of class '<em>Transition State</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Transition State</em>'.
   * @generated
   */
  TransitionState createTransitionState();

  /**
   * Returns a new object of class '<em>Trigger</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Trigger</em>'.
   * @generated
   */
  Trigger createTrigger();

  /**
   * Returns a new object of class '<em>Action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Action</em>'.
   * @generated
   */
  Action createAction();

  /**
   * Returns a new object of class '<em>Occurrence</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Occurrence</em>'.
   * @generated
   */
  Occurrence createOccurrence();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  DepModelPackage getDepModelPackage();

} //DepModelFactory
