/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Port Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortDec()
 * @model
 * @generated
 */
public interface ErrorPortDec extends ErrorModelElement
{
} // ErrorPortDec
