/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Port In</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ErrorPortIn#getErrorPortInName <em>Error Port In Name</em>}</li>
 *   <li>{@link hu.bme.mit.depModel.ErrorPortIn#getErrorPortInSuperType <em>Error Port In Super Type</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortIn()
 * @model
 * @generated
 */
public interface ErrorPortIn extends ErrorPortDec
{
  /**
   * Returns the value of the '<em><b>Error Port In Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error Port In Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Port In Name</em>' attribute.
   * @see #setErrorPortInName(String)
   * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortIn_ErrorPortInName()
   * @model
   * @generated
   */
  String getErrorPortInName();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ErrorPortIn#getErrorPortInName <em>Error Port In Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error Port In Name</em>' attribute.
   * @see #getErrorPortInName()
   * @generated
   */
  void setErrorPortInName(String value);

  /**
   * Returns the value of the '<em><b>Error Port In Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error Port In Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Port In Super Type</em>' reference.
   * @see #setErrorPortInSuperType(PortType)
   * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortIn_ErrorPortInSuperType()
   * @model
   * @generated
   */
  PortType getErrorPortInSuperType();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ErrorPortIn#getErrorPortInSuperType <em>Error Port In Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error Port In Super Type</em>' reference.
   * @see #getErrorPortInSuperType()
   * @generated
   */
  void setErrorPortInSuperType(PortType value);

} // ErrorPortIn
