/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Port Out</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ErrorPortOut#getErrorPortOutSuperType <em>Error Port Out Super Type</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortOut()
 * @model
 * @generated
 */
public interface ErrorPortOut extends ErrorPortDec
{
  /**
   * Returns the value of the '<em><b>Error Port Out Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error Port Out Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Port Out Super Type</em>' reference.
   * @see #setErrorPortOutSuperType(PortType)
   * @see hu.bme.mit.depModel.DepModelPackage#getErrorPortOut_ErrorPortOutSuperType()
   * @model
   * @generated
   */
  PortType getErrorPortOutSuperType();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ErrorPortOut#getErrorPortOutSuperType <em>Error Port Out Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error Port Out Super Type</em>' reference.
   * @see #getErrorPortOutSuperType()
   * @generated
   */
  void setErrorPortOutSuperType(PortType value);

} // ErrorPortOut
