/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Modes</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ErrorModes#getErrorModeName <em>Error Mode Name</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getErrorModes()
 * @model
 * @generated
 */
public interface ErrorModes extends EObject
{
  /**
   * Returns the value of the '<em><b>Error Mode Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error Mode Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error Mode Name</em>' attribute.
   * @see #setErrorModeName(String)
   * @see hu.bme.mit.depModel.DepModelPackage#getErrorModes_ErrorModeName()
   * @model
   * @generated
   */
  String getErrorModeName();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.ErrorModes#getErrorModeName <em>Error Mode Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error Mode Name</em>' attribute.
   * @see #getErrorModeName()
   * @generated
   */
  void setErrorModeName(String value);

} // ErrorModes
