/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Error Model Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.ErrorModelDec#getEmodelElements <em>Emodel Elements</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getErrorModelDec()
 * @model
 * @generated
 */
public interface ErrorModelDec extends ComponentFeaturesDec
{
  /**
   * Returns the value of the '<em><b>Emodel Elements</b></em>' containment reference list.
   * The list contents are of type {@link hu.bme.mit.depModel.ErrorModelElement}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Emodel Elements</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Emodel Elements</em>' containment reference list.
   * @see hu.bme.mit.depModel.DepModelPackage#getErrorModelDec_EmodelElements()
   * @model containment="true"
   * @generated
   */
  EList<ErrorModelElement> getEmodelElements();

} // ErrorModelDec
