/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurrence</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getOccurrence()
 * @model
 * @generated
 */
public interface Occurrence extends TransitionFeatureDec
{
} // Occurrence
