/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Port In</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link hu.bme.mit.depModel.PortIn#getPortInName <em>Port In Name</em>}</li>
 *   <li>{@link hu.bme.mit.depModel.PortIn#getPortInSuperType <em>Port In Super Type</em>}</li>
 * </ul>
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getPortIn()
 * @model
 * @generated
 */
public interface PortIn extends PortDec
{
  /**
   * Returns the value of the '<em><b>Port In Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port In Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port In Name</em>' attribute.
   * @see #setPortInName(String)
   * @see hu.bme.mit.depModel.DepModelPackage#getPortIn_PortInName()
   * @model
   * @generated
   */
  String getPortInName();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.PortIn#getPortInName <em>Port In Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port In Name</em>' attribute.
   * @see #getPortInName()
   * @generated
   */
  void setPortInName(String value);

  /**
   * Returns the value of the '<em><b>Port In Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port In Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port In Super Type</em>' reference.
   * @see #setPortInSuperType(PortType)
   * @see hu.bme.mit.depModel.DepModelPackage#getPortIn_PortInSuperType()
   * @model
   * @generated
   */
  PortType getPortInSuperType();

  /**
   * Sets the value of the '{@link hu.bme.mit.depModel.PortIn#getPortInSuperType <em>Port In Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port In Super Type</em>' reference.
   * @see #getPortInSuperType()
   * @generated
   */
  void setPortInSuperType(PortType value);

} // PortIn
