/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>State Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getStateDec()
 * @model
 * @generated
 */
public interface StateDec extends ErrorModelElement
{
} // StateDec
