/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sys Features Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see hu.bme.mit.depModel.DepModelPackage#getSysFeaturesDec()
 * @model
 * @generated
 */
public interface SysFeaturesDec extends EObject
{
} // SysFeaturesDec
