/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class DepModelUiModule extends AbstractDepModelUiModule {
}
