/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.ui.tests;

import com.google.inject.Injector;
import hu.bme.mit.DepModel.ui.internal.DepModelActivator;
import org.eclipse.xtext.junit4.IInjectorProvider;

public class DepModelUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DepModelActivator.getInstance().getInjector("hu.bme.mit.DepModel");
	}

}
