/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DepModelRuntimeModule extends AbstractDepModelRuntimeModule {
}
