/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel.util;

import hu.bme.mit.depModel.*;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.common.notify.impl.AdapterFactoryImpl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * The <b>Adapter Factory</b> for the model.
 * It provides an adapter <code>createXXX</code> method for each class of the model.
 * <!-- end-user-doc -->
 * @see hu.bme.mit.depModel.DepModelPackage
 * @generated
 */
public class DepModelAdapterFactory extends AdapterFactoryImpl
{
  /**
   * The cached model package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static DepModelPackage modelPackage;

  /**
   * Creates an instance of the adapter factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DepModelAdapterFactory()
  {
    if (modelPackage == null)
    {
      modelPackage = DepModelPackage.eINSTANCE;
    }
  }

  /**
   * Returns whether this factory is applicable for the type of the object.
   * <!-- begin-user-doc -->
   * This implementation returns <code>true</code> if the object is either the model's package or is an instance object of the model.
   * <!-- end-user-doc -->
   * @return whether this factory is applicable for the type of the object.
   * @generated
   */
  @Override
  public boolean isFactoryForType(Object object)
  {
    if (object == modelPackage)
    {
      return true;
    }
    if (object instanceof EObject)
    {
      return ((EObject)object).eClass().getEPackage() == modelPackage;
    }
    return false;
  }

  /**
   * The switch that delegates to the <code>createXXX</code> methods.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DepModelSwitch<Adapter> modelSwitch =
    new DepModelSwitch<Adapter>()
    {
      @Override
      public Adapter caseDepModel(DepModel object)
      {
        return createDepModelAdapter();
      }
      @Override
      public Adapter caseAbstractElement(AbstractElement object)
      {
        return createAbstractElementAdapter();
      }
      @Override
      public Adapter casePortType(PortType object)
      {
        return createPortTypeAdapter();
      }
      @Override
      public Adapter caseErrorModes(ErrorModes object)
      {
        return createErrorModesAdapter();
      }
      @Override
      public Adapter caseComponentModelDec(ComponentModelDec object)
      {
        return createComponentModelDecAdapter();
      }
      @Override
      public Adapter caseSystemConnDec(SystemConnDec object)
      {
        return createSystemConnDecAdapter();
      }
      @Override
      public Adapter caseSystemDec(SystemDec object)
      {
        return createSystemDecAdapter();
      }
      @Override
      public Adapter caseSysFeaturesDec(SysFeaturesDec object)
      {
        return createSysFeaturesDecAdapter();
      }
      @Override
      public Adapter caseSystemPortDec(SystemPortDec object)
      {
        return createSystemPortDecAdapter();
      }
      @Override
      public Adapter caseSystemPortIn(SystemPortIn object)
      {
        return createSystemPortInAdapter();
      }
      @Override
      public Adapter caseSystemPortOut(SystemPortOut object)
      {
        return createSystemPortOutAdapter();
      }
      @Override
      public Adapter caseComponentConnDec(ComponentConnDec object)
      {
        return createComponentConnDecAdapter();
      }
      @Override
      public Adapter caseComponentImpl(ComponentImpl object)
      {
        return createComponentImplAdapter();
      }
      @Override
      public Adapter caseComponentType(ComponentType object)
      {
        return createComponentTypeAdapter();
      }
      @Override
      public Adapter caseComponentFeaturesDec(ComponentFeaturesDec object)
      {
        return createComponentFeaturesDecAdapter();
      }
      @Override
      public Adapter casePortDec(PortDec object)
      {
        return createPortDecAdapter();
      }
      @Override
      public Adapter casePortIn(PortIn object)
      {
        return createPortInAdapter();
      }
      @Override
      public Adapter casePortOut(PortOut object)
      {
        return createPortOutAdapter();
      }
      @Override
      public Adapter caseErrorModelDec(ErrorModelDec object)
      {
        return createErrorModelDecAdapter();
      }
      @Override
      public Adapter caseErrorModelElement(ErrorModelElement object)
      {
        return createErrorModelElementAdapter();
      }
      @Override
      public Adapter caseErrorPortDec(ErrorPortDec object)
      {
        return createErrorPortDecAdapter();
      }
      @Override
      public Adapter caseErrorPortIn(ErrorPortIn object)
      {
        return createErrorPortInAdapter();
      }
      @Override
      public Adapter caseErrorPortOut(ErrorPortOut object)
      {
        return createErrorPortOutAdapter();
      }
      @Override
      public Adapter caseStateDec(StateDec object)
      {
        return createStateDecAdapter();
      }
      @Override
      public Adapter caseTransitionDec(TransitionDec object)
      {
        return createTransitionDecAdapter();
      }
      @Override
      public Adapter caseTransitionFeatureDec(TransitionFeatureDec object)
      {
        return createTransitionFeatureDecAdapter();
      }
      @Override
      public Adapter caseTransitionState(TransitionState object)
      {
        return createTransitionStateAdapter();
      }
      @Override
      public Adapter caseTriggerDec(TriggerDec object)
      {
        return createTriggerDecAdapter();
      }
      @Override
      public Adapter caseActionDec(ActionDec object)
      {
        return createActionDecAdapter();
      }
      @Override
      public Adapter caseOccurrenceDec(OccurrenceDec object)
      {
        return createOccurrenceDecAdapter();
      }
      @Override
      public Adapter defaultCase(EObject object)
      {
        return createEObjectAdapter();
      }
    };

  /**
   * Creates an adapter for the <code>target</code>.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param target the object to adapt.
   * @return the adapter for the <code>target</code>.
   * @generated
   */
  @Override
  public Adapter createAdapter(Notifier target)
  {
    return modelSwitch.doSwitch((EObject)target);
  }


  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.DepModel <em>Dep Model</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.DepModel
   * @generated
   */
  public Adapter createDepModelAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.AbstractElement <em>Abstract Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.AbstractElement
   * @generated
   */
  public Adapter createAbstractElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.PortType <em>Port Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.PortType
   * @generated
   */
  public Adapter createPortTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorModes <em>Error Modes</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorModes
   * @generated
   */
  public Adapter createErrorModesAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ComponentModelDec <em>Component Model Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ComponentModelDec
   * @generated
   */
  public Adapter createComponentModelDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SystemConnDec <em>System Conn Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SystemConnDec
   * @generated
   */
  public Adapter createSystemConnDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SystemDec <em>System Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SystemDec
   * @generated
   */
  public Adapter createSystemDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SysFeaturesDec <em>Sys Features Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SysFeaturesDec
   * @generated
   */
  public Adapter createSysFeaturesDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SystemPortDec <em>System Port Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SystemPortDec
   * @generated
   */
  public Adapter createSystemPortDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SystemPortIn <em>System Port In</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SystemPortIn
   * @generated
   */
  public Adapter createSystemPortInAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.SystemPortOut <em>System Port Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.SystemPortOut
   * @generated
   */
  public Adapter createSystemPortOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ComponentConnDec <em>Component Conn Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ComponentConnDec
   * @generated
   */
  public Adapter createComponentConnDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ComponentImpl <em>Component Impl</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ComponentImpl
   * @generated
   */
  public Adapter createComponentImplAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ComponentType <em>Component Type</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ComponentType
   * @generated
   */
  public Adapter createComponentTypeAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ComponentFeaturesDec <em>Component Features Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ComponentFeaturesDec
   * @generated
   */
  public Adapter createComponentFeaturesDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.PortDec <em>Port Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.PortDec
   * @generated
   */
  public Adapter createPortDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.PortIn <em>Port In</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.PortIn
   * @generated
   */
  public Adapter createPortInAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.PortOut <em>Port Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.PortOut
   * @generated
   */
  public Adapter createPortOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorModelDec <em>Error Model Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorModelDec
   * @generated
   */
  public Adapter createErrorModelDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorModelElement <em>Error Model Element</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorModelElement
   * @generated
   */
  public Adapter createErrorModelElementAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorPortDec <em>Error Port Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorPortDec
   * @generated
   */
  public Adapter createErrorPortDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorPortIn <em>Error Port In</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorPortIn
   * @generated
   */
  public Adapter createErrorPortInAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ErrorPortOut <em>Error Port Out</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ErrorPortOut
   * @generated
   */
  public Adapter createErrorPortOutAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.StateDec <em>State Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.StateDec
   * @generated
   */
  public Adapter createStateDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.TransitionDec <em>Transition Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.TransitionDec
   * @generated
   */
  public Adapter createTransitionDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.TransitionFeatureDec <em>Transition Feature Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.TransitionFeatureDec
   * @generated
   */
  public Adapter createTransitionFeatureDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.TransitionState <em>Transition State</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.TransitionState
   * @generated
   */
  public Adapter createTransitionStateAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.TriggerDec <em>Trigger Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.TriggerDec
   * @generated
   */
  public Adapter createTriggerDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.ActionDec <em>Action Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.ActionDec
   * @generated
   */
  public Adapter createActionDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for an object of class '{@link hu.bme.mit.depModel.OccurrenceDec <em>Occurrence Dec</em>}'.
   * <!-- begin-user-doc -->
   * This default implementation returns null so that we can easily ignore cases;
   * it's useful to ignore a case when inheritance will catch all the cases anyway.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @see hu.bme.mit.depModel.OccurrenceDec
   * @generated
   */
  public Adapter createOccurrenceDecAdapter()
  {
    return null;
  }

  /**
   * Creates a new adapter for the default case.
   * <!-- begin-user-doc -->
   * This default implementation returns null.
   * <!-- end-user-doc -->
   * @return the new adapter.
   * @generated
   */
  public Adapter createEObjectAdapter()
  {
    return null;
  }

} //DepModelAdapterFactory
