/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.ui.contentassist;

import hu.bme.mit.ui.contentassist.AbstractDepModelProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DepModelProposalProvider extends AbstractDepModelProposalProvider {
}
