/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.validation;

import hu.bme.mit.validation.AbstractDepModelValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class DepModelValidator extends AbstractDepModelValidator {
}
