/**
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.depModel.impl;

import hu.bme.mit.depModel.ComponentModelDec;
import hu.bme.mit.depModel.DepModelPackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Component Model Dec</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ComponentModelDecImpl extends AbstractElementImpl implements ComponentModelDec
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComponentModelDecImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return DepModelPackage.Literals.COMPONENT_MODEL_DEC;
  }

} //ComponentModelDecImpl
