/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractDepModelScopeProvider extends DelegatingScopeProvider {
}
