/*
 * generated by Xtext 2.9.2
 */
package hu.bme.mit.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.parser.antlr.internal.InternalDepModelParser;
import hu.bme.mit.services.DepModelGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class DepModelParser extends AbstractAntlrParser {

	@Inject
	private DepModelGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalDepModelParser createParser(XtextTokenStream stream) {
		return new InternalDepModelParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "DepModel";
	}

	public DepModelGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DepModelGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
